from pathlib import Path
from html import escape
import json

ROOT = Path(__file__).resolve().parents[1]
SITE = 'https://cloudempiretech.github.io/CharviBoutique/'

pages = {
    '': ('Charvi Boutique | Handloom Sarees & Ethnic Wear in Ballygunge, Kolkata', 'Explore handloom sarees, salwars, kurtis and home textiles at Charvi Boutique in Ballygunge, Kolkata. Discover the boutique and get in touch.', 'Home'),
    'about/': ('Our Story | Charvi Boutique, Kolkata', 'Learn about Charvi Boutique, a Ballygunge destination for handloom sarees and ethnic wear since 2009.', 'Our Story'),
    'collections/': ('Collections | Sarees, Ethnic Wear & Home Textiles | Charvi Boutique', 'Browse the types of handloom sarees, salwars, kurtis and home textiles offered at Charvi Boutique in Ballygunge.', 'Collections'),
    'collections/sarees/': ('Handloom Sarees in Ballygunge | Charvi Boutique', 'Explore Charvi Boutique’s saree selection, including cotton handloom, tussar, Chanderi and Dupion silk in Kolkata.', 'Sarees'),
    'collections/salwar-kurtis/': ('Salwars & Kurtis in Ballygunge | Charvi Boutique', 'Discover ethnic wear at Charvi Boutique in Kolkata, including salwars and kurtis. Contact the boutique about current availability.', 'Salwars & Kurtis'),
    'collections/home-textiles/': ('Home Textiles | Charvi Boutique, Ballygunge', 'Ask Charvi Boutique about its bed cover selection and home textiles at the Ballygunge shop in Kolkata.', 'Home Textiles'),
    'gallery/': ('Boutique Gallery | Charvi Boutique, Kolkata', 'View genuine photographs of Charvi Boutique’s saree displays and boutique collection in Ballygunge, Kolkata.', 'Gallery'),
    'testimonials/': ('Customer Words | Charvi Boutique, Kolkata', 'Read a publicly shared customer comment about Charvi Boutique’s sarees and find links to independent reviews.', 'Customer Words'),
    'faq/': ('Frequently Asked Questions | Charvi Boutique, Kolkata', 'Answers to common questions about Charvi Boutique’s sarees, ethnic wear, location and how to enquire.', 'FAQs'),
    'contact/': ('Contact & Visit | Charvi Boutique, Ballygunge', 'Call or WhatsApp Charvi Boutique, visit its Ballygunge shop at 4B Baman Para Lane, or send an enquiry.', 'Contact'),
}

icons = '''<svg xmlns="http://www.w3.org/2000/svg" class="icon-sprite" aria-hidden="true"><symbol id="i-arrow" viewBox="0 0 24 24"><path d="M4 12h15m-6-6 6 6-6 6"/></symbol><symbol id="i-phone" viewBox="0 0 24 24"><path d="M7 3H4a1 1 0 0 0-1 1c0 9.4 7.6 17 17 17a1 1 0 0 0 1-1v-3l-5-2-2 2a15 15 0 0 1-7-7l2-2-2-5Z"/></symbol><symbol id="i-pin" viewBox="0 0 24 24"><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></symbol><symbol id="i-insta" viewBox="0 0 24 24"><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></symbol><symbol id="i-facebook" viewBox="0 0 24 24"><path d="M14 21v-8h3l.5-4H14V7c0-1 .4-1.5 1.6-1.5H18V2h-3c-3.4 0-5 1.8-5 5v2H7v4h3v8"/></symbol><symbol id="i-whatsapp" viewBox="0 0 24 24"><path d="M20.5 11.6a8.5 8.5 0 0 1-12.4 7.5L3 20.5l1.4-5.1a8.5 8.5 0 1 1 16.1-3.8Z"/><path d="M8.5 8.5c.4 3.3 3.2 6.2 6.5 6.8l1.5-1.5-2.3-1.2-1.1 1a7 7 0 0 1-2.8-2.8l1-1.1-1.3-2.2-1.5 1Z"/></symbol><symbol id="i-menu" viewBox="0 0 24 24"><path d="M3 7h18M3 12h18M3 17h18"/></symbol><symbol id="i-close" viewBox="0 0 24 24"><path d="M5 5 19 19M19 5 5 19"/></symbol><symbol id="i-plus" viewBox="0 0 24 24"><path d="M12 4v16M4 12h16"/></symbol></svg>'''

def icon(name): return f'<svg class="icon" aria-hidden="true"><use href="#i-{name}"></use></svg>'
def link(path, here):
    if path.startswith(('https://','http://','tel:','mailto:')): return path
    depth = len([x for x in here.split('/') if x]); return ('../' * depth) + path if path else ('../' * depth or './')
def photo(n, alt, here, cls='', loading='lazy'):
    if n == 0:
        return '<div class="abstract-art" aria-hidden="true"><span class="fabric-fold fold-1"></span><span class="fabric-fold fold-2"></span><span class="fabric-fold fold-3"></span><span class="fabric-seal">C<span>✦</span>B</span></div>'
    p=link('assets/images/', here)
    wide = 720 if n==3 else 960
    priority = ' fetchpriority="high"' if loading=='eager' else ''
    return f'<picture class="{cls}"><source type="image/webp" srcset="{p}boutique-{n}-480.webp 480w, {p}boutique-{n}-960.webp {wide}w" sizes="(max-width: 700px) 90vw, 44vw"><img src="{p}boutique-{n}.jpg" alt="{escape(alt)}" loading="{loading}" decoding="async"{priority} width="{wide}" height="{906 if n==3 else 720}"></picture>'
def button(text, dest, here, cls='btn btn-gold'):
    return f'<a class="{cls}" href="{link(dest,here)}"><span>{text}</span>{icon("arrow")}</a>'
def external_button(text, dest, cls='btn btn-gold'):
    return f'<a class="{cls}" href="{dest}" target="_blank" rel="noopener noreferrer"><span>{text}</span>{icon("arrow")}</a>'
def heading(kicker,title,body=''):
    return f'<div class="section-head reveal"><span class="eyebrow">{kicker}</span><h2>{title}</h2>{f"<p>{body}</p>" if body else ""}</div>'
def collection_cards(here):
    data=[('01','The Saree Edit','Cotton handloom, tant, mulmul, tussar, Chanderi and Dupion silk.', 'collections/sarees/','saree'),('02','Salwars & Kurtis','Everyday and occasion-ready ethnic wear, selected in person.', 'collections/salwar-kurtis/','wear'),('03','Home Textiles','Bed covers that bring textile character into living spaces.', 'collections/home-textiles/','home')]
    return '<div class="collection-grid">'+''.join(f'<a class="collection-card tilt reveal {c}" href="{link(url,here)}"><span class="card-number">{num}</span><span class="card-orbit" aria-hidden="true"></span><span class="card-bottom"><strong>{title}</strong><small>{desc}</small><span class="round-arrow">{icon("arrow")}</span></span></a>' for num,title,desc,url,c in data)+'</div>'
def contact_band(here):
    return f'<section class="contact-band"><div class="contact-band-inner reveal"><span class="eyebrow">Make it personal</span><h2>Find your next<br><em>favourite drape.</em></h2><p>Ask about what is currently in the boutique, or plan a visit to Ballygunge.</p><div class="button-row">{button("Enquire on WhatsApp","https://wa.me/919831132890",here)}{button("Plan your visit","contact/",here,"btn btn-outline-light")}</div></div><div class="band-orb" aria-hidden="true"></div></section>'

content = {}
content[''] = lambda h: f'''
<section class="home-hero hero-depth"><div class="hero-glow" aria-hidden="true"></div><div class="hero-grid container"><div class="hero-copy"><span class="eyebrow hero-reveal">Ballygunge, Kolkata · Since <span class="counter" data-count="2009">2009</span></span><h1 class="hero-reveal">Wear the<br><em>art of living.</em></h1><p class="hero-reveal">Handloom sarees and thoughtful ethnic wear, discovered one beautiful detail at a time at Charvi Boutique.</p><div class="button-row hero-reveal">{button('Explore collections','collections/',h)}{button('Visit the boutique','contact/',h,'btn btn-outline-light')}</div><div class="hero-social hero-reveal"><span>Follow the story</span><a href="https://www.instagram.com/thecharviboutique/?hl=en" aria-label="Instagram" target="_blank" rel="noopener noreferrer">{icon('insta')}</a><a href="https://www.facebook.com/Charviboutique/" aria-label="Facebook" target="_blank" rel="noopener noreferrer">{icon('facebook')}</a></div></div><div class="hero-stage" data-parallax><div class="stage-ring"></div><div class="stage-back">{photo(1,'Saree display inside Charvi Boutique',h,'stage-image','eager')}</div><div class="stage-main">{photo(3,'Printed saree draped on a mannequin at Charvi Boutique',h,'stage-image','eager')}<span class="image-stamp">The Charvi edit <b>✦</b> Kolkata</span></div><div class="stage-glass"><span class="sparkle">✦</span><span>Threads of<br><em>tradition</em></span></div><div class="stage-disk"></div></div></div><div class="hero-bottom container"><span>01 / 03</span><span>Scroll to discover ↓</span><span>Curated in Kolkata</span></div></section>
<section class="intro section-pad container"><div class="intro-symbol reveal" aria-hidden="true">✦</div><div class="intro-text reveal"><span class="eyebrow">A boutique with a point of view</span><h2>For the days that deserve <em>something memorable.</em></h2><p>From the texture of cotton handloom to the quiet lustre of silk, Charvi Boutique brings together sarees, salwars, kurtis and home textiles for people who love the details.</p>{button('Meet Charvi Boutique','about/',h,'text-link')}</div><div class="intro-aside reveal"><span class="line"></span><p>Explore at your own pace. See the fabrics, colours and drapes up close in Ballygunge.</p></div></section>
<section class="collections-section section-pad"><div class="container">{heading('Discover the collection','Texture tells the story.','Explore the categories available at Charvi Boutique. For current pieces and colours, call or send a message.')}{collection_cards(h)}</div></section>
<section class="feature-section section-pad container"><div class="feature-media reveal"><div class="photo-shadow"></div>{photo(2,'Green embroidered saree displayed on a mannequin at Charvi Boutique',h,'feature-photo','eager')}<div class="feature-tag">A closer look <span>↗</span></div></div><div class="feature-copy reveal"><span class="eyebrow">The handloom edit</span><h2>A feel for<br><em>every fabric.</em></h2><p>Explore cotton handloom sarees such as tant and mulmul, alongside the character of tussar, Chanderi and Dupion silk. Each material has its own movement, texture and mood.</p><ul class="material-list"><li><span>01</span> Cotton handloom</li><li><span>02</span> Tussar & Chanderi</li><li><span>03</span> Dupion silk</li></ul>{button('Explore sarees','collections/sarees/',h,'text-link')}</div></section>
<section class="quote-section section-pad"><div class="container quote-layout"><div class="quote-star reveal" aria-hidden="true">✳</div><div class="reveal"><span class="eyebrow">Customer words</span><blockquote>“Very nice sarees”</blockquote><p>— Obhijit D, Google review shared on Wanderlog, November 2021</p>{button('Read customer words','testimonials/',h,'text-link')}</div></div></section>
{contact_band(h)}'''

content['about/'] = lambda h: f'''<section class="page-hero about-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">The story so far</span><h1 class="hero-reveal">A love of<br><em>the weave.</em></h1><p class="hero-reveal">A Ballygunge boutique for ethnic wear, handloom textures and everyday expression.</p></div><div class="page-hero-art">{photo(1,'Sarees hanging inside Charvi Boutique in Ballygunge',h,'page-art-photo','eager')}<span class="art-circle"></span></div></div></section><section class="section-pad container split-story"><div class="reveal"><span class="eyebrow">Charvi Boutique</span><h2>Rooted in Kolkata.<br><em>Drawn to detail.</em></h2></div><div class="story-prose reveal"><p>Charvi Boutique has offered ethnic wear in Kolkata since <strong>2009</strong>. Its collection includes sarees, salwars, kurtis and bed covers, with a particular focus on handloom materials.</p><p>In the boutique, fabric takes centre stage: the lightness of mulmul, the familiarity of tant, the texture of tussar and the soft sheen of Chanderi or Dupion silk. Visit to see the current selection in person.</p>{button('Explore collections','collections/',h,'text-link')}</div></section><section class="values-section section-pad"><div class="container">{heading('What you will find','A collection of contrasts.')}<div class="value-grid"><article class="value-card tilt reveal"><span>01</span><h3>Everyday ease</h3><p>Cotton handloom sarees for the pleasure of a comfortable, expressive drape.</p></article><article class="value-card tilt reveal"><span>02</span><h3>Occasion texture</h3><p>Tussar, Chanderi and Dupion silk for moments that ask for another kind of presence.</p></article><article class="value-card tilt reveal"><span>03</span><h3>Beyond sarees</h3><p>Salwars, kurtis and bed covers round out the boutique’s textile selection.</p></article></div></div></section>{contact_band(h)}'''

content['collections/'] = lambda h: f'''<section class="page-hero collection-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">Discover Charvi</span><h1 class="hero-reveal">The curated<br><em>collection.</em></h1><p class="hero-reveal">Sarees, ethnic wear and home textiles with colour, texture and character.</p></div><div class="page-hero-art fabric-art" aria-hidden="true"><span class="fabric-fold fold-1"></span><span class="fabric-fold fold-2"></span><span class="fabric-fold fold-3"></span><span class="fabric-seal">C<span>✦</span>B</span></div></div></section><section class="section-pad container">{heading('Browse by category','Find your point of view.','Categories reflect the boutique’s known range. Contact us for the pieces currently available.')}{collection_cards(h)}</section><section class="section-pad collection-note"><div class="container split-story"><div class="reveal"><span class="eyebrow">In person is different</span><h2>See how it<br><em>moves.</em></h2></div><div class="story-prose reveal"><p>Texture and colour can feel different in person. Visit the Ballygunge boutique to explore the current edit, or get in touch before you come.</p>{button('Plan your visit','contact/',h)}</div></div></section>'''

def detail(h, category, title, intro, image_num, alt, materials, text):
    chips=''.join(f'<span>{x}</span>' for x in materials)
    return f'''<section class="page-hero detail-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">Collections / {category}</span><h1 class="hero-reveal">{title}</h1><p class="hero-reveal">{intro}</p><div class="button-row hero-reveal">{external_button('Ask what is in store','https://wa.me/919831132890?text=Hello%20Charvi%20Boutique%2C%20I%27d%20like%20to%20ask%20about%20'+category.replace(' ','%20')+'.')}{button('Browse all collections','collections/',h,'btn btn-outline-light')}</div></div><div class="page-hero-art">{photo(image_num,alt,h,'page-art-photo','eager')}<span class="art-circle"></span></div></div></section><section class="section-pad container split-story"><div class="reveal"><span class="eyebrow">In the boutique</span><h2>Explore the<br><em>details.</em></h2></div><div class="story-prose reveal"><p>{text}</p><div class="chip-row">{chips}</div><p>Selection changes. Call or message the boutique for current availability, colours and more details.</p>{button('Contact Charvi Boutique','contact/',h,'text-link')}</div></section><section class="section-pad more-collections"><div class="container">{heading('Keep exploring','The collection continues.')}{collection_cards(h)}</div></section>{contact_band(h)}'''
content['collections/sarees/']=lambda h:detail(h,'Sarees','Sarees with<br><em>a story.</em>','From airy cotton handloom to the distinct character of silk and Chanderi.',3,'Printed saree displayed at Charvi Boutique',['Tant','Mulmul','Tussar','Chanderi','Dupion silk'],'Charvi Boutique is known for handloom sarees, including cotton styles such as tant and mulmul, and materials such as tussar, Chanderi and Dupion silk. The weave, border and drape make each choice personal.')
content['collections/salwar-kurtis/']=lambda h:detail(h,'Salwars & Kurtis','Easy to wear.<br><em>Hard to forget.</em>','Ethnic wear to discover alongside the boutique’s saree collection.',0,'',['Salwars','Kurtis','Ethnic wear'],'Alongside its sarees, Charvi Boutique offers salwars and kurtis. Explore the colours and styles at the Ballygunge shop, or enquire about the current selection before your visit.')
content['collections/home-textiles/']=lambda h:detail(h,'Home Textiles','A touch of<br><em>textile at home.</em>','Bring a love of fabric beyond the wardrobe.',0,'',['Bed covers','Textile details'],'Bed covers are part of Charvi Boutique’s wider textile range. Speak with the boutique to learn what colours, patterns and materials are currently available.')

content['gallery/']=lambda h: f'''<section class="page-hero gallery-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">Inside the boutique</span><h1 class="hero-reveal">The Charvi<br><em>gallery.</em></h1><p class="hero-reveal">A glimpse of sarees and displays photographed at Charvi Boutique in Ballygunge.</p></div><div class="page-hero-art">{photo(2,'Green embroidered saree on display at Charvi Boutique',h,'page-art-photo','eager')}<span class="art-circle"></span></div></div></section><section class="section-pad container">{heading('Real views','Colour, pattern, presence.','Photographs of the boutique’s displays. These images show past selections; ask the boutique about the current collection.')}<div class="gallery-grid"><button class="gallery-item reveal" type="button" data-lightbox="1" aria-label="Enlarge photograph of saree display in Charvi Boutique">{photo(1,'Rack of colourful sarees inside Charvi Boutique',h)}<span>01 / Inside Charvi <b>↗</b></span></button><button class="gallery-item reveal tall" type="button" data-lightbox="3" aria-label="Enlarge photograph of printed saree">{photo(3,'Printed saree draped on a mannequin at Charvi Boutique',h)}<span>02 / Draped detail <b>↗</b></span></button><button class="gallery-item reveal" type="button" data-lightbox="2" aria-label="Enlarge photograph of green saree">{photo(2,'Green embroidered saree on a mannequin at Charvi Boutique',h)}<span>03 / Colour & embroidery <b>↗</b></span></button></div></section><dialog class="lightbox" aria-label="Gallery photo"><button type="button" class="lightbox-close" aria-label="Close image">{icon('close')}</button><img alt=""><p></p></dialog>{contact_band(h)}'''

content['testimonials/']=lambda h: f'''<section class="page-hero text-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">From a customer</span><h1 class="hero-reveal">A kind<br><em>word lasts.</em></h1><p class="hero-reveal">A publicly shared comment about the boutique’s sarees.</p></div><div class="page-hero-art type-art" aria-hidden="true">“<span>✦</span></div></div></section><section class="section-pad container review-wrap"><span class="quote-mark reveal">“</span><blockquote class="reveal">Very nice sarees</blockquote><p class="reveal">Obhijit D · Google review dated 28 November 2021, shown on Wanderlog</p>{external_button('Read the source','https://wanderlog.com/place/details/10475224/charvi-boutique','text-link')}<div class="review-note reveal"><h2>See the collection for yourself.</h2><p>Photographs and short reviews offer a glimpse. Visit the shop or get in touch to find out what is available now.</p>{button('Visit Charvi Boutique','contact/',h)}</div></section>'''

faq=[('Where is Charvi Boutique?','The boutique is listed at 4B Baman Para Lane, near Ballygunge Phari, Ballygunge, Kolkata, West Bengal 700019.'),('What does Charvi Boutique sell?','The known range includes sarees, salwars, kurtis and bed covers. Its saree selection includes handloom materials such as cotton, tussar, Chanderi and Dupion silk.'),('Can I see current pieces online?','The gallery shows past displays. For current pieces, colours or availability, please call or message the boutique directly.'),('How can I contact the boutique?','Call +91 98311 32890 or +91 94772 25097. You can also send a WhatsApp message to the primary number.'),('Do you list prices or online checkout?','Prices and online checkout are not provided here. Please contact the boutique for details on a piece you are interested in.'),('Can I visit in person?','Yes. Use the address and directions on our contact page. Calling ahead is a good way to confirm the latest opening times and availability.')]
content['faq/']=lambda h:f'''<section class="page-hero text-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">Good to know</span><h1 class="hero-reveal">Your questions,<br><em>answered.</em></h1><p class="hero-reveal">Useful details before you explore or visit.</p></div><div class="page-hero-art type-art question-art" aria-hidden="true">?<span>✦</span></div></div></section><section class="section-pad container faq-layout"><div class="faq-intro reveal"><span class="eyebrow">FAQs</span><h2>Here to help<br><em>you find it.</em></h2><p>Need a detail about a specific piece? The boutique can tell you what is currently available.</p>{button('Ask on WhatsApp','https://wa.me/919831132890',h,'text-link')}</div><div class="faq-list">{''.join(f'<details class="faq-item reveal"><summary>{escape(q)}<span>{icon("plus")}</span></summary><p>{escape(a)}</p></details>' for q,a in faq)}</div></section>{contact_band(h)}'''

content['contact/']=lambda h:f'''<section class="page-hero contact-hero"><div class="container page-hero-grid"><div class="page-hero-copy"><span class="eyebrow hero-reveal">Visit or say hello</span><h1 class="hero-reveal">Come closer<br><em>to the craft.</em></h1><p class="hero-reveal">The best way to discover a fabric is to see it, feel it and ask about it.</p></div><div class="page-hero-art">{photo(1,'Clothing rack inside Charvi Boutique in Ballygunge',h,'page-art-photo','eager')}<span class="art-circle"></span></div></div></section><section class="section-pad container contact-grid"><div class="contact-info reveal"><span class="eyebrow">Find us in Ballygunge</span><h2>We would love<br><em>to hear from you.</em></h2><div class="contact-line">{icon('pin')}<div><strong>Visit the boutique</strong><p>4B Baman Para Lane, near Ballygunge Phari,<br>Ballygunge, Kolkata, West Bengal 700019</p><a href="https://www.google.com/maps/search/?api=1&query=Charvi+Boutique+4B+Baman+Para+Lane+Ballygunge+Kolkata" target="_blank" rel="noopener noreferrer">Open directions ↗</a></div></div><div class="contact-line">{icon('phone')}<div><strong>Call us</strong><p><a href="tel:+919831132890">+91 98311 32890</a><br><a href="tel:+919477225097">+91 94772 25097</a></p></div></div><div class="contact-line">{icon('whatsapp')}<div><strong>Message us</strong><p><a href="https://wa.me/919831132890" target="_blank" rel="noopener noreferrer">WhatsApp Charvi Boutique ↗</a></p></div></div><div class="social-row"><a href="https://www.instagram.com/thecharviboutique/?hl=en" aria-label="Instagram" target="_blank" rel="noopener noreferrer">{icon('insta')}</a><a href="https://www.facebook.com/Charviboutique/" aria-label="Facebook" target="_blank" rel="noopener noreferrer">{icon('facebook')}</a></div></div><form class="enquiry-form reveal" id="enquiry-form"><span class="eyebrow">An easy first step</span><h2>Send an enquiry.</h2><p>Tell us what you are looking for. Your message will open in WhatsApp for you to send.</p><label for="name">Your name</label><input id="name" name="name" autocomplete="name" required placeholder="Your name"><label for="interest">I am interested in</label><select id="interest" name="interest"><option>Sarees</option><option>Salwars & kurtis</option><option>Home textiles</option><option>Visiting the boutique</option><option>Something else</option></select><label for="message">Your message</label><textarea id="message" name="message" rows="4" required placeholder="Tell us what you would like to know"></textarea><button class="btn btn-gold" type="submit"><span>Continue to WhatsApp</span>{icon('arrow')}</button><p class="form-status" role="status"></p></form></section>'''

def nav(h):
    items=[('Home',''),('Our Story','about/'),('Collections','collections/'),('Gallery','gallery/'),('Customer Words','testimonials/'),('FAQs','faq/'),('Contact','contact/')]
    return '<nav class="site-nav" id="site-nav" aria-label="Main navigation">'+''.join(f'<a href="{link(p,h)}" {"aria-current=\"page\"" if p==h else ""}>{label}</a>' for label,p in items)+'</nav>'
def footer(h):
    return f'''<footer class="site-footer"><div class="container footer-main"><div class="footer-brand"><a class="brand footer-logo" href="{link('',h)}" aria-label="Charvi Boutique home"><span class="brand-mark">C<span>✦</span>B</span><span class="brand-name">Charvi <small>BOUTIQUE</small></span></a><p>A world of sarees, ethnic wear and textile detail in Ballygunge, Kolkata.</p></div><div class="footer-links"><h3>Explore</h3><a href="{link('about/',h)}">Our Story</a><a href="{link('collections/',h)}">Collections</a><a href="{link('gallery/',h)}">Gallery</a><a href="{link('faq/',h)}">FAQs</a></div><div class="footer-links"><h3>Discover</h3><a href="{link('collections/sarees/',h)}">Sarees</a><a href="{link('collections/salwar-kurtis/',h)}">Salwars & Kurtis</a><a href="{link('collections/home-textiles/',h)}">Home Textiles</a><a href="{link('testimonials/',h)}">Customer Words</a></div><div class="footer-contact"><h3>Get in touch</h3><a href="tel:+919831132890">{icon('phone')} +91 98311 32890</a><a href="https://wa.me/919831132890" target="_blank" rel="noopener noreferrer">{icon('whatsapp')} WhatsApp</a><a href="https://www.google.com/maps/search/?api=1&query=Charvi+Boutique+4B+Baman+Para+Lane+Ballygunge+Kolkata" target="_blank" rel="noopener noreferrer">{icon('pin')} Ballygunge, Kolkata</a><div class="social-row"><a href="https://www.instagram.com/thecharviboutique/?hl=en" aria-label="Instagram" target="_blank" rel="noopener noreferrer">{icon('insta')}</a><a href="https://www.facebook.com/Charviboutique/" aria-label="Facebook" target="_blank" rel="noopener noreferrer">{icon('facebook')}</a></div></div></div><div class="container footer-bottom"><span>© 2026 Charvi Boutique. All rights reserved.</span><span>Developed by <a href="https://cloudempire.tech/" target="_blank" rel="noopener noreferrer">Cloudempire</a></span></div></footer>'''

def page(h, title, desc, label):
    css=link('assets/css/style.css',h); js=link('assets/js/site.js',h)
    canonical=f'<link rel="canonical" href="{SITE+h}">' if SITE else ''
    data={'@context':'https://schema.org','@type':'ClothingStore','name':'Charvi Boutique','url':SITE,'telephone':['+91 98311 32890','+91 94772 25097'],'address':{'@type':'PostalAddress','streetAddress':'4B Baman Para Lane','addressLocality':'Kolkata','addressRegion':'West Bengal','postalCode':'700019','addressCountry':'IN'},'sameAs':['https://www.facebook.com/Charviboutique/','https://www.instagram.com/thecharviboutique/']}
    schema='<script type="application/ld+json">'+json.dumps(data,ensure_ascii=False)+'</script>'
    return f'''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#24131e"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}">{canonical}<meta property="og:type" content="website"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:image" content="{SITE}assets/images/boutique-3.jpg"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,500&display=swap" rel="stylesheet"><link rel="stylesheet" href="{css}">{schema}<script src="{js}" defer></script></head><body data-page="{label}">{icons}<a class="skip-link" href="#main">Skip to content</a><div class="page-transition" aria-hidden="true"></div><header class="site-header"><div class="container header-inner"><a class="brand" href="{link('',h)}" aria-label="Charvi Boutique home"><span class="brand-mark">C<span>✦</span>B</span><span class="brand-name">Charvi <small>BOUTIQUE</small></span></a>{nav(h)}<div class="header-actions"><a href="https://www.instagram.com/thecharviboutique/?hl=en" aria-label="Instagram" target="_blank" rel="noopener noreferrer">{icon('insta')}</a><a href="https://wa.me/919831132890" aria-label="WhatsApp Charvi Boutique" target="_blank" rel="noopener noreferrer">{icon('whatsapp')}</a><a class="header-contact" href="{link('contact/',h)}">Let's talk {icon('arrow')}</a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="site-nav">{icon('menu')}</button></div></div></header><main id="main">{content[h](h)}</main>{footer(h)}<a class="float-whatsapp" href="https://wa.me/919831132890" aria-label="Chat with Charvi Boutique on WhatsApp" target="_blank" rel="noopener noreferrer">{icon('whatsapp')}</a></body></html>'''

for h,(title,desc,label) in pages.items():
    file=ROOT/h/'index.html'; file.parent.mkdir(parents=True,exist_ok=True); file.write_text(page(h,title,desc,label),encoding='utf8')

(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{SITE+h}</loc></url>\n' for h in pages)+'</urlset>\n',encoding='utf8')
(ROOT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {SITE}sitemap.xml\n',encoding='utf8')
